
{
    "code": 0,
    "msg": "",
    "count": 100,
    "data": [{
      "id": "1",
      "asin": "B0CLLXFLF6",
      "categorySort":"639",
      "category":"in Jewellery",
      "name":"国旗地图锁骨链",
      "site": "加拿大",
      "brand":"Peraca Cris",
      "weight": "20",
      "exchangeRate":"5.00",
      "purchasePrice": "10.00",
      "price":"20.00",
      "fba": "4.9",
      "priceRate":"2.37",
      "procureUrl":"https://www.baidu.com",
      "image":"https://img.zcool.cn/community/01705555452efa0000019ae984a1ac.jpg@1280w_1l_2o_100sh.jpg",
      "status":"",
      "createTime":"",
      "firstCheckTime":"",
      "secondCheckTime":"",
      "checker":"",
      "desc":"",
      "ownerUserId":""
    },{
        "id": "1",
        "asin": "B0CLLXFLF6",
        "categorySort":"639",
        "category":"in Jewellery",
        "name":"国旗地图锁骨链",
        "site": "加拿大",
        "brand":"Peraca Cris",
        "weight": "20",
        "exchangeRate":"5.00",
        "purchasePrice": "10.00",
        "price":"20.00",
        "fba": "4.9",
        "priceRate":"2.37",
        "procureUrl":"https://www.baidu.com",
        "image":"",
        "status":"",
        "createTime":"",
        "firstCheckTime":"",
        "secondCheckTime":"",
        "checker":"",
        "desc":"",
        "ownerUserId":""
      },{
        "id": "1",
        "asin": "B0CLLXFLF6",
        "categorySort":"639",
        "category":"in Jewellery",
        "name":"国旗地图锁骨链",
        "site": "加拿大",
        "brand":"Peraca Cris",
        "weight": "20",
        "exchangeRate":"5.00",
        "purchasePrice": "10.00",
        "price":"20.00",
        "fba": "4.9",
        "priceRate":"2.37",
        "procureUrl":"https://www.baidu.com",
        "image":"",
        "status":"",
        "createTime":"",
        "firstCheckTime":"",
        "secondCheckTime":"",
        "checker":"",
        "desc":"",
        "ownerUserId":""
      },{
        "id": "1",
        "asin": "B0CLLXFLF6",
        "categorySort":"639",
        "category":"in Jewellery",
        "name":"国旗地图锁骨链",
        "site": "加拿大",
        "brand":"Peraca Cris",
        "weight": "20",
        "exchangeRate":"5.00",
        "purchasePrice": "10.00",
        "price":"20.00",
        "fba": "4.9",
        "priceRate":"2.37",
        "procureUrl":"https://www.baidu.com",
        "image":"",
        "status":"",
        "createTime":"",
        "firstCheckTime":"",
        "secondCheckTime":"",
        "checker":"",
        "desc":"",
        "ownerUserId":""
      },{
        "id": "1",
        "asin": "B0CLLXFLF6",
        "categorySort":"639",
        "category":"in Jewellery",
        "name":"国旗地图锁骨链",
        "site": "加拿大",
        "brand":"Peraca Cris",
        "weight": "20",
        "exchangeRate":"5.00",
        "purchasePrice": "10.00",
        "price":"20.00",
        "fba": "4.9",
        "priceRate":"2.37",
        "procureUrl":"https://www.baidu.com",
        "image":"https://img.zcool.cn/community/01705555452efa0000019ae984a1ac.jpg@1280w_1l_2o_100sh.jpg",
        "status":"",
        "createTime":"",
        "firstCheckTime":"",
        "secondCheckTime":"",
        "checker":"",
        "desc":"",
        "ownerUserId":""
      },{
          "id": "1",
          "asin": "B0CLLXFLF6",
          "categorySort":"639",
          "category":"in Jewellery",
          "name":"国旗地图锁骨链",
          "site": "加拿大",
          "brand":"Peraca Cris",
          "weight": "20",
          "exchangeRate":"5.00",
          "purchasePrice": "10.00",
          "price":"20.00",
          "fba": "4.9",
          "priceRate":"2.37",
          "procureUrl":"https://www.baidu.com",
          "image":"",
          "status":"",
          "createTime":"",
          "firstCheckTime":"",
          "secondCheckTime":"",
          "checker":"",
          "desc":"",
          "ownerUserId":""
        },{
          "id": "1",
          "asin": "B0CLLXFLF6",
          "categorySort":"639",
          "category":"in Jewellery",
          "name":"国旗地图锁骨链",
          "site": "加拿大",
          "brand":"Peraca Cris",
          "weight": "20",
          "exchangeRate":"5.00",
          "purchasePrice": "10.00",
          "price":"20.00",
          "fba": "4.9",
          "priceRate":"2.37",
          "procureUrl":"https://www.baidu.com",
          "image":"",
          "status":"",
          "createTime":"",
          "firstCheckTime":"",
          "secondCheckTime":"",
          "checker":"",
          "desc":"",
          "ownerUserId":""
        },{
          "id": "1",
          "asin": "B0CLLXFLF6",
          "categorySort":"639",
          "category":"in Jewellery",
          "name":"国旗地图锁骨链",
          "site": "加拿大",
          "brand":"Peraca Cris",
          "weight": "20",
          "exchangeRate":"5.00",
          "purchasePrice": "10.00",
          "price":"20.00",
          "fba": "4.9",
          "priceRate":"2.37",
          "procureUrl":"https://www.baidu.com",
          "image":"",
          "status":"",
          "createTime":"",
          "firstCheckTime":"",
          "secondCheckTime":"",
          "checker":"",
          "desc":"",
          "ownerUserId":""
        },{
            "id": "1",
            "asin": "B0CLLXFLF6",
            "categorySort":"639",
            "category":"in Jewellery",
            "name":"国旗地图锁骨链",
            "site": "加拿大",
            "brand":"Peraca Cris",
            "weight": "20",
            "exchangeRate":"5.00",
            "purchasePrice": "10.00",
            "price":"20.00",
            "fba": "4.9",
            "priceRate":"2.37",
            "procureUrl":"https://www.baidu.com",
            "image":"https://img.zcool.cn/community/01705555452efa0000019ae984a1ac.jpg@1280w_1l_2o_100sh.jpg",
            "status":"",
            "createTime":"",
            "firstCheckTime":"",
            "secondCheckTime":"",
            "checker":"",
            "desc":"",
            "ownerUserId":""
          },{
              "id": "1",
              "asin": "B0CLLXFLF6",
              "categorySort":"639",
              "category":"in Jewellery",
              "name":"国旗地图锁骨链",
              "site": "加拿大",
              "brand":"Peraca Cris",
              "weight": "20",
              "exchangeRate":"5.00",
              "purchasePrice": "10.00",
              "price":"20.00",
              "fba": "4.9",
              "priceRate":"2.37",
              "procureUrl":"https://www.baidu.com",
              "image":"",
              "status":"",
              "createTime":"",
              "firstCheckTime":"",
              "secondCheckTime":"",
              "checker":"",
              "desc":"",
              "ownerUserId":""
            },{
              "id": "1",
              "asin": "B0CLLXFLF6",
              "categorySort":"639",
              "category":"in Jewellery",
              "name":"国旗地图锁骨链",
              "site": "加拿大",
              "brand":"Peraca Cris",
              "weight": "20",
              "exchangeRate":"5.00",
              "purchasePrice": "10.00",
              "price":"20.00",
              "fba": "4.9",
              "priceRate":"2.37",
              "procureUrl":"https://www.baidu.com",
              "image":"",
              "status":"",
              "createTime":"",
              "firstCheckTime":"",
              "secondCheckTime":"",
              "checker":"",
              "desc":"",
              "ownerUserId":""
            },{
              "id": "1",
              "asin": "B0CLLXFLF6",
              "categorySort":"639",
              "category":"in Jewellery",
              "name":"国旗地图锁骨链",
              "site": "加拿大",
              "brand":"Peraca Cris",
              "weight": "20",
              "exchangeRate":"5.00",
              "purchasePrice": "10.00",
              "price":"20.00",
              "fba": "4.9",
              "priceRate":"2.37",
              "procureUrl":"https://www.baidu.com",
              "image":"",
              "status":"",
              "createTime":"",
              "firstCheckTime":"",
              "secondCheckTime":"",
              "checker":"",
              "desc":"",
              "ownerUserId":""
            }]
  }